name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Setup windows-rs dependency
      shell: bash
      run: |
        cp -r reactor_patches ../reactor_patches
        mkdir -p ../_lib
        cd ../_lib
        git clone https://github.com/microsoft/windows-rs.git
        cd windows-rs
        git checkout a4f7b2cb7c63c6bb7fc77a2affe57145be1d8c4f
        cp ../../reactor_patches/* crates/libs/reactor/src/
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check --workspace
    - name: Clippy
      run: cargo clippy --workspace
    - name: Test
      run: cargo test --workspace
