name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          src:
            - '**'
            - '!**/*.md'
            - '!docs/**'
            - '!.github/ISSUE_TEMPLATE/**'
            - '!.gitignore'

  build:
    needs: filter
    if: ${{ needs.filter.outputs.src == 'true' }}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Setup windows-rs dependency
      shell: bash
      run: |
        cp -r reactor_patches ../reactor_patches
        mkdir -p ../_lib/windows-rs
        cd ../_lib/windows-rs
        git init
        git remote add origin https://github.com/microsoft/windows-rs.git
        git fetch --depth 1 origin a4f7b2cb7c63c6bb7fc77a2affe57145be1d8c4f
        git reset --hard FETCH_HEAD
        cp ../../reactor_patches/* crates/libs/reactor/src/
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check --workspace
    - name: Clippy
      run: cargo clippy --workspace
    - name: Test
      run: cargo test --workspace

  ci-success:
    runs-on: ubuntu-latest
    needs: [filter, build]
    if: always()
    steps:
      - name: Verify CI Status
        run: |
          if [ "${{ needs.build.result }}" == "failure" ] || [ "${{ needs.build.result }}" == "cancelled" ]; then
            echo "Build failed or was cancelled."
            exit 1
          fi
          echo "Build passed or was successfully skipped!"
