name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Setup windows-rs dependency
      run: |
        mkdir -p ../_lib
        cd ../_lib
        git clone https://github.com/microsoft/windows-rs.git
        cd windows-rs
        git checkout a4f7b2cb7c63c6bb7fc77a2affe57145be1d8c4f
        git apply ${{ github.workspace }}/windows-rs.patch
    - name: Build Release Artifacts
      run: .\build_release.ps1
      shell: powershell
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          twedit-portable-release.zip
          twedit-ui\target\wix\*.msi
        generate_release_notes: true
